import "./globals.css";
import { Poppins } from "next/font/google";
import { AuthContextProvider } from "@/lib/context/AuthContext";
import ModalProvider from "@/lib/context/ModalContext";
import { CartProvider } from "@/lib/context/CartContext";
import { dir } from "i18next";
import { languages, fallbackLng } from "../i18n/settings";
import { useTranslation } from "../i18n";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from "@vercel/analytics/react";
import { getCurrentUser, isUserAuthenticated } from "@/lib/authentication/firebaseAdmin";

const poppins = Poppins({
	display: "swap",
	subsets: ["latin"],
	variable: "--poppins-font",
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {

	return languages.map((lang) => ({ lang }));

};

export default async function RootLayout({ 
	children,
	params: {
		lang
	}
}) {

	const user = await getCurrentUser();

	return (

		<html lang={lang} dir={dir(lang)}>

			<AuthContextProvider>

				<CartProvider user={user ? user.uid : null} >
					<ModalProvider>

						<body className={poppins.className}>
							{children}
							{/* <SpeedInsights /> */}
						</body>

					</ModalProvider>
				</CartProvider>

			</AuthContextProvider>

		</html>

	);

};
