import "./globals.css";
import { Poppins } from "next/font/google";
import { AuthContextProvider } from "@/lib/context/AuthContext";
import ModalProvider from "@/lib/context/ModalContext";
import { CartProvider } from "@/lib/context/CartContext";
import { dir } from "i18next";
import { languages, fallbackLng } from "../i18n/settings";
import { useTranslation } from "../i18n";

const poppins = Poppins({
	display: "swap",
	subsets: ["latin"],
	variable: "--poppins-font",
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {

	return languages.map((lang) => ({ lang }));

};

export default function RootLayout({ 
	children,
	params: {
		lang
	}
}) {

	return (

		<html lang={lang} dir={dir(lang)}>

			<AuthContextProvider>
				<CartProvider>
					<ModalProvider>

						<body  className={poppins.className}>{children}</body>

					</ModalProvider>
				</CartProvider>
			</AuthContextProvider>

		</html>

	);

};
