import "./globals.css";
import { poppins } from "@/styles/fonts";
import AuthContextProvider from "@/lib/context/AuthContext";
import ModalProvider from "@/lib/context/ModalContext";
import { languages, fallbackLng } from "./i18n/settings";
import { cookies, headers } from "next/headers";
import Head from "next/head";
import { storageKeys } from "@/lib/constants/settings.config";
import { getCurrentUser } from "@/lib/authentication/sessionHelpers";
import { captureException } from "@sentry/nextjs";
import { captureEvent, captureNavigation } from "@/lib/analytics/client";

const baseUrl = "https://www.thelongitudebrand.com";

export const metadata = {

	metadataBase: new URL(baseUrl),
	title: {
		default: "Longitude Official Site",
		template: "%s | Longitude Official"
	},
	description: "Generated by create next app",
	robots: {
		follow: true,
		index: true
	},
	alternates: {
		canonical: `${baseUrl}/`,
		languages: {
			"en-EN": "/en",
			"fr-FR": "/fr"
		}
	}

};

export async function generateStaticParams() {

	return languages.map((lang) => ({ lang }));

};

// async function captureNavigation(headers) {

// 	try {

// 		const cookieStore = cookies();

// 		const payload = {
// 			path: headers.get("x-pathname"),
// 			referer: headers.get("referer"),
// 			userAgent: headers.get("x-user-agent"),
// 			distinctId: cookieStore.get(storageKeys.ANALYTICS_SESSION_ID),
// 			propreties: {
// 				clientIp: headers.get("x-real-ip")
// 			},
// 		};

// 		await captureEvent("page view", payload);

// 	} catch (err) {

// 		captureException(err);

// 	};

// };

export default async function RootLayout({
	children,
}) {

	const structuredData = JSON.stringify({
		"@context": "https://schema.org",
		"@type": "Organization",
		name: "Longitude",
		url: baseUrl,
		logo: `${baseUrl}/logo.png`,
	});

	const headersList = headers();
	let lang = headersList.has("x-language") ? headersList.get("x-language") : fallbackLng;

	// handleNavigationTracking(headersList);

	await captureNavigation();

	return (

		<html lang={lang}>

			<Head>
				<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: structuredData }} />
			</Head>

			<AuthContextProvider>

				<ModalProvider>

						<body className={poppins.className}>
							{children}
							{/* <SpeedInsights /> */}
						</body>

				</ModalProvider>

			</AuthContextProvider>

		</html>

	);

};
