import "./globals.css";
import { poppins } from "@/styles/fonts";
import AuthContextProvider from "@/lib/context/AuthContext";
import ModalProvider from "@/lib/context/ModalContext";
import { languages, fallbackLng } from "./i18n/settings";
import { headers } from "next/headers";
import Head from "next/head";
import { captureNavigation } from "@/lib/analytics/client";

const baseUrl = "https://www.thelongitudebrand.com";
const isDev = (process.env.NODE_ENV || "production") == "development";

export const metadata = {

	metadataBase: new URL(baseUrl),
	title: {
		default: "Longitude Official Site",
		template: "%s | Longitude Official"
	},
	description: "Generated by create next app",
	robots: {
		follow: true,
		index: true
	},
	alternates: {
		canonical: `${baseUrl}/`,
		languages: {
			"en-EN": "/en",
			"fr-FR": "/fr"
		}
	}

};

export async function generateStaticParams() {

	return languages.map((lang) => ({ lang }));

};

export default async function RootLayout({
	children,
}) {

	const structuredData = JSON.stringify({
		"@context": "https://schema.org",
		"@type": "Organization",
		name: "Longitude",
		url: baseUrl,
		logo: `${baseUrl}/logo.png`,
	});

	const headersList = headers();
	let lang = headersList.has("x-language") ? headersList.get("x-language") : fallbackLng;

	// handleNavigationTracking(headersList);

	if (!isDev) await captureNavigation();

	return (

		<html lang={lang}>

			<Head>
				<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: structuredData }} />
			</Head>

			<AuthContextProvider>

				<ModalProvider>

						<body className={poppins.className}>
							{children}
							{/* <SpeedInsights /> */}
						</body>

				</ModalProvider>

			</AuthContextProvider>

		</html>

	);

};
