import "./globals.css";
import { Poppins } from "next/font/google";
import { AuthContextProvider } from "@/lib/context/AuthContext";
import ModalProvider from "@/lib/context/ModalContext";
import { CartProvider } from "@/lib/context/CartContext";
import { languages, fallbackLng } from "./i18n/settings";
import { useTranslation } from "./i18n";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from "@vercel/analytics/react";
import { getCurrentUser } from "@/lib/authentication/sessionHelpers";
import { headers } from "next/headers";

const poppins = Poppins({
	display: "swap",
	subsets: ["latin"],
	variable: "--poppins-font",
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
	metadataBase: new URL("https://thelongitudebrand.com"),
	title: {
		default: "Longitude Official Site",
		template: "%s | Longitude Official"
	},
	description: "Generated by create next app",
};

export async function generateStaticParams() {

	return languages.map((lang) => ({ lang }));

};

export default async function RootLayout({ 
	children,
}) {

	let lang;

	const headersList = headers();
	lang = headersList.has("x-language") ? headersList.get("x-languge") : fallbackLng;

	const user = await getCurrentUser();

	return (

		<html lang={lang}>

			<AuthContextProvider>

				<CartProvider user={user ? user.uid : null} >
					<ModalProvider>

						<body className={poppins.className}>
							{children}
							{/* <SpeedInsights /> */}
						</body>

					</ModalProvider>
				</CartProvider>

			</AuthContextProvider>

		</html>

	);

};
